plugin:
  name: OctoFilament
  identifier: octoprint_octofilament
  version: 0.3.0
  description: Plugin para detectar presencia de filamento y mostrar estado en la interfaz
  author: Alfonso
  pythoncompat: ">=3.7,<4"
  homepage: https://github.com/alfonso/octofilament
  type: plugin
  packages:
    - octoprint_octofilament
